apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: ${BE_LABEL}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ${BE_LABEL}
    spec:
      containers:
      - name: ${BE_LABEL}
        image: ${BE_IMG}:${BE_TAG}
        ports:
        - containerPort: 6379
